services:
  postgres:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brighte_eats_db
    ports:
      - "5433:5432" # Expose PostgreSQL on port 5433 changing the original port 5432 to avoid conflicts
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
